# Generated by Django 5.0.6 on 2024-07-01 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='created',
        ),
    ]
